[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
argh.workspace = true
futures-util = "0.3.31"
indicatif = "0.17.11"
reqwest = { version = "0.12.15", features = ["stream"] }
tokio = { version = "1.44.1", features = ["full"] }
